name: Template ci

on:
  push:
    branches: [ main, 'feature/*' ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build and Test
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:

      - name: Checkout current branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run the template through sbt new
        run: |
          sbt new file://$(pwd) --name=testproject --force

      - name: Grant permissions to nix folder
        run: |
          sudo mkdir -p /nix/store
          sudo chmod -R 777 /nix

      - name: Cache nix
        uses: actions/cache@v3
        with:
         path: |
          # See https://github.com/actions/cache/pull/726
          /nix/store/**
          # Missing something?
          /nix/var/nix/*/*
          /nix/var/nix/db/*
          /nix/var/nix/db/*/**
          !/nix/var/nix/daemon-socket/socket
          !/nix/var/nix/userpool/*
          !/nix/var/nix/gc.lock
          !/nix/var/nix/db/big-lock
          !/nix/var/nix/db/reserved
         key: ${{ runner.os }}-nix-store

      - name: Install nix
        uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Check cache hits
        shell: bash
        run: |
          echo "Cache hit: ${{steps.get-cache.outputs.cache-hit}}"

      - name: Compile generated project
        run: |
          cd testproject
          nix-shell --pure --run "gradle --no-watch-fs --console=plain --no-daemon --info testDebug assembleDebug"

      - name: Check artifact existence
        uses: andstor/file-existence-action@v2
        with:
          fail: true
          files: "testproject/app/build/outputs/apk/debug/app-debug.apk"
